### ISSUE TITLE
Customize id types per object

### ISSUE THREAD

**Issue by jaalfaro** [rse/graphql-tools-sequelize#5]
If I understand correctly, I can only have 1 types of id for all of my classes.  Is that correct, so, I could set options in new GraphQLToolsSequelize(sequelize, options), but if say, I set it to string, it applies to everything, so I can't use an int as a id.

Thanks

**Comment by rse** [comment]
Yes, correct. The id always has to be of the same type for all entities. Usually this is a technical id based on a UUID. It doesn't prevent you from also having a domain-specific additional id of an arbitrary type, of course. But the technical id has to be named "id" and be of the same type.
