### ISSUE TITLE
Query child objects

### ISSUE THREAD

**Issue by jaalfaro** [rse/graphql-tools-sequelize#7]
I'm trying to figure out if its possible to query child objects.  I've looked at 3 options that I've been unable to work with.  Given a query such as 
objectlevel1s {
  field1
  field2
  objectlevel2s {
    field1
    field2 
  }
}

I know I can use the where construct to query level 1, but I want to limit level 2 returned items.  So far, I've tried 
1. objectlevel1s (where: {objectlevel2: {field1: "value"}})
2. objectlevel1s(where: {"objectlevel2.field1": "value"})
3. objectlevel2s (where: {field1: "value"})

None of those seem to work.  Is what I want to do even possible?  Thanks.

**Comment by rse** [comment]
What about `objectlevel1s { field1 field2 objectlevel2s(where: { field1: "value" }) { field1 field2 } }`?

**Comment by jaalfaro** [comment]
That gives me an error "GraphQLError: Unknown argument \"where\" on field \"objectlevel2s\" of type \"objectlevel1s\". from graphql/validation/rules/KnownArgumentNames.js.  

It appears the deeper objects are not getting the setup for the query options.  

I'm not seeing how to make that happen.  Is that even possible?

**Comment by rse** [comment]
How do your resolvers look like? Especially the resolver objectlevel1s.objectlevel2s?

**Comment by jaalfaro** [comment]
Staff: {
            allocations: gts.entityQueryResolver("Staff", "AllocationsStaffIdFks", "Allocation*"),
...

**Comment by jaalfaro** [comment]
OK.  So I figured it out. It's not the resolved thats the problem, but the definition.  What was missing is something like 
Staff: {
        ${gts.entityQuerySchema("Staff", "allocations", "Allocation*")}
...

which replaced:
Staff: {
       allocations: [Allocation]
....

There just wasn't an example of that.  Replaced and all is well.
